
server:
 port: 8888
spring:
 jackson:
  date-format: yyyy-MM-dd HH:mm:ss
 devtools:
  estart:
   enabled: true
   additional-paths: src/main/java
   exclude: test/**,templates/**
 datasource:
  driver-class-name: com.mysql.jdbc.Driver
  username: root
  password:
  url: jdbc:mysql://localhost:3307/qichefuwu?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8
 thymeleaf:
  cache: false #关闭缓存
 servlet:
  multipart:
   max-file-size: 100MB
   max-request-size: 100MB

mybatis-plus:
 mapper-locations: classpath:mapper/*.xml
 type-aliases-package: com.example.entity
 configuration:
  map-underscore-to-camel-case: true
  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
 global-config:
  db-config:
   id-type: input
   capital-mode: true
   update-strategy: not_null
   insert-strategy: not_empty
   select-strategy: not_empty

pagehelper:
 helper-dialect: mysql
 reasonable: true
 support-methods-arguments: true
 params: count=countSql

authority:
 info: '[{"models":[{"modelId":1,"operation":[1,2,3,4]},{"modelId":1000001,"operation":[1,2,3,4]},{"modelId":1000009,"operation":[1,2,3,4]},{"modelId":1000010,"operation":[1,2,3,4]},{"modelId":1000016,"operation":[1,2,3,4]},{"modelId":1000011,"operation":[1,2,3,4]},{"modelId":1000013,"operation":[1,2,3,4]},{"modelId":2,"operation":[1,2,3,4]}],"level":1,"modelId":1,"name":"图书商店管理员"},{"models":[{"modelId":3,"operation":[1,2,3,4]},{"modelId":1000009,"operation":[4]},{"modelId":1000015,"operation":[1,2,3,4]},{"modelId":1000012,"operation":[1,2,3,4]},{"modelId":1000016,"operation":[1,2,3,4]},{"modelId":1000014,"operation":[1,2,3,4]}],"level":2,"modelId":2,"name":"教务处"},{"models":[{"modelId":1000009,"operation":[4]},{"modelId":1000012,"operation":[1,2,3,4]},{"modelId":1000015,"operation":[1,2,3,4]},{"modelId":1000014,"operation":[4]}],"level":3,"modelId":3,"name":"用户"}]'

#日志配置
logging:
 level:
  root: warn
  com.example.dao: trace
  com.example: trace
